'use client';
import {EquipmentArt, EquipmentInventory, SafehouseMintPanel} from './equipment-inventory';
import { ArrowRight, Check, Flame, Gem, Hammer, LockKeyhole, Sparkles, TrendingUp } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { CHAPTERS, type ChapterId } from '@/lib/campaign';
import { HEROES, ITEMS, type Run, type HeroId, type ItemId } from '@/lib/game';
import { canEnterChapter, itemDescription, levelFor, upgradeCost, XP_THRESHOLDS, type RecordBook } from '@/lib/progression';
export function CampaignSelect({book,chapter,onSelect,disabled=false}:{book:RecordBook;chapter:ChapterId;onSelect:(id:ChapterId)=>void;disabled?:boolean}){
 return <div className="campaign-selector" aria-label="Choose a district">{CHAPTERS.map(c=>{const unlocked=canEnterChapter(book,c.id),cleared=book.cleared.includes(c.id);return <button key={c.id} disabled={disabled||!unlocked} aria-pressed={c.id===chapter} onClick={()=>onSelect(c.id)} className={`campaign-card campaign-${c.id} ${c.id===chapter?'selected':''} ${cleared?'cleared':''}`}><span className="campaign-art" style={{backgroundImage:`url('/climb/assets/art/${c.art}.png')`,backgroundSize:'300% 300%',backgroundPosition:c.artPosition}}/><span className="campaign-roman">{c.roman}</span><span className="campaign-copy"><small>LEVEL {c.roman} · {c.difficulty}</small><strong>{c.name}</strong><span>{cleared?<><Check size={12}/> District liberated</>:unlocked?`Level ${c.recommendedLevel}+ · Boss overclock reward`:<><LockKeyhole size={12}/> Liberate Level {CHAPTERS[c.id-2].roman}</>}</span></span><span className="campaign-status">{!unlocked?<LockKeyhole size={16}/>:c.id===chapter?<Check size={17}/>:<ArrowRight size={16}/>}</span></button>;})}</div>;
}
export default function Camp({run,book,active,onTrain,onUpgrade,onSelectChapter,onReady,onMint,onEquip}:{run:Run;book:RecordBook;active:boolean;onTrain:(id:HeroId)=>void;onUpgrade:(id:ItemId)=>void;onSelectChapter:(id:ChapterId)=>void;onReady:()=>void;onMint:()=>void;onEquip:(id:string)=>void}){
 const chapter=CHAPTERS[run.chapter-1];return <div className="camp-tab"><div className="camp-heading"><div><span className="small-label gold">THE UNDERGROUND / REBEL LOGISTICS</span><h1>Safehouse & Armory</h1><p>Train your faction. Mint equipment. Prepare the next climb.</p></div><div className="bank-balance"><Gem size={22}/><div><strong>{book.salvage}</strong><span>OFF-CHAIN CREDITS AVAILABLE</span></div></div></div>
 <CampaignSelect book={book} chapter={run.chapter} onSelect={onSelectChapter} disabled={active}/>
 <div className="chapter-preparation"><span className="preparation-icon"><Flame size={22}/></span><div><strong>Prepare for {chapter.name}</strong><p>{chapter.mechanic} Recommended: level {chapter.recommendedLevel}+. Improve your loadout before departure and overclock it after bosses.</p></div><button className="primary-button" onClick={onReady}>{active?'Resume operation':'View operation'}<ArrowRight size={16}/></button></div>
 {active&&<p className="camp-lock"><LockKeyhole size={15}/> Your climb keeps its current loadout and temporary overclocks. Newly minted items are available for your next climb.</p>}
 <div className="camp-section-title"><span className="small-label">01 / OPERATIVE MASTERY</span><span>Experience stays with each character—even after a failed operation.</span></div>
 <div className="mastery-grid">{HEROES.map(h=>{const xp=book.xp[h.id],level=levelFor(xp),next=XP_THRESHOLDS[level],start=XP_THRESHOLDS[level-1],progress=level===12?100:(xp-start)/(next-start)*100;return <article className={`mastery-card ${run.heroId===h.id?'current':''}`} key={h.id}><div className="mastery-hero"><span className={`portrait portrait-${h.portrait}`}/><div><small>{h.title}</small><h2>{h.name}</h2></div><span className="level-medal"><small>LVL</small>{level}</span></div><div className="xp-label"><span>{level===12?'Mastery complete':`${xp-start} / ${next-start} XP to level ${level+1}`}</span><b>{xp} XP</b></div><Progress value={progress} aria-label={`${h.name} experience`} className="meter xp-meter"/><div className="mastery-bonuses"><span>+{(level-1)*5} health</span><span>+{level-1} attack</span><span>+{(level-1)*2} skill</span></div><p>{level>=4?'Mastery unlocked: signature abilities recover in 2 turns.':'At level 4: signature cooldown falls from 3 turns to 2.'}</p><button className="training-button" disabled={active||book.salvage<75||level===12} onClick={()=>onTrain(h.id)}><TrendingUp size={15}/>{level===12?'Maximum level':'Train · +80 XP'}<span><Gem size={12}/>75</span></button></article>;})}</div>
 <div className="camp-section-title"><span className="small-label">02 / THE ARMORY</span><span>Filter your inventory by slot. Permanent items stay; boss overclocks last one climb.</span></div>
 <SafehouseMintPanel book={book} onMint={onMint}/><EquipmentInventory book={book} run={run} active={active} onEquip={onEquip} compact/><div className="camp-footer"><Gem size={16}/><p>Bank credits by securing districts. Minted equipment remains yours after a failed climb.</p><span>{book.lifetimeSalvage} lifetime credits</span></div></div>;
}
