'use client';
import { useState, type CSSProperties } from 'react';
import { Check, Gem, Shield, Sparkles } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { RARITIES, SLOTS, equipmentText, SAFEHOUSE_MINT_COST, equippedItem, type Equipment } from '@/lib/equipment';
import { climbBoost, upgradeBenefit, itemFor, type Run, type ItemId, type Slot } from '@/lib/game';
import { itemDescription, type RecordBook } from '@/lib/progression';

export function EquipmentArt({id,className=''}:{id:ItemId;className?:string}){
 const item=itemFor(id),boxes=['0 0 627 550','627 0 627 550','0 550 627 704','627 550 627 704'];
 return item.art<6?<span role="img" aria-label={item.name} className={`item-art item-art-${item.art} ${className}`}/>:<svg role="img" aria-label={item.name} className={`item-art equipment-new-art ${className}`} viewBox={boxes[item.art-6]} overflow="hidden"><image href="/climb/assets/art/alpha-equipment-expansion.png" width="1254" height="1254"/></svg>;
}
export function EquipmentInventory({book,run,active,onEquip,compact=false}:{book:RecordBook;run:Run;active:boolean;onEquip:(id:string)=>void;compact?:boolean}){
 const [slot,setSlot]=useState<Slot|'all'>(compact?'weapon':'all'),[selected,setSelected]=useState<Equipment|null>(null);
 return <section className={`inventory-system ${compact?'armory-compact':''}`}><div className="inventory-filters" aria-label="Equipment slots">{(['all',...SLOTS] as const).map(s=><button key={s} aria-pressed={slot===s} onClick={()=>setSlot(s)}>{s==='all'?'All equipment':s}</button>)}</div><div className="inventory-grid">{book.inventory.filter(i=>slot==='all'||i.slot===slot).sort((a,b)=>Number(equippedItem(run,b.slot)?.id===b.id)-Number(equippedItem(run,a.slot)?.id===a.id)||b.rarity-a.rarity||b.quality-a.quality).map(i=>{const base=itemFor(i.baseId),rarity=RARITIES[i.rarity],selected=equippedItem(run,i.slot)?.id===i.id;return <button key={i.id} className={`inventory-card ${selected?'selected':''}`} style={{'--rarity':rarity.color} as CSSProperties} onClick={()=>setSelected(i)}><EquipmentArt id={i.baseId}/><span className="inventory-copy"><small>{i.slot} · {rarity.name}</small><strong>{base.name}</strong><span>{i.damageType??base.effect}</span><em>Quality {i.quality}/3{book.ranks[i.baseId]>0?` · Legacy +${book.ranks[i.baseId]}`:''}{selected&&climbBoost(run,i.slot)>0?` · Climb +${climbBoost(run,i.slot)}`:''}</em></span>{selected&&<Check size={17}/>}</button>;})}</div><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="hollow-dialog equipment-dialog">{selected&&<><EquipmentArt id={selected.baseId} className="dialog-item-art"/><span className="rarity-label" style={{color:RARITIES[selected.rarity].color}}>{RARITIES[selected.rarity].tier} · {RARITIES[selected.rarity].name} · {selected.slot}</span><DialogTitle>{itemFor(selected.baseId).name}</DialogTitle><DialogDescription>{itemDescription(selected.baseId,book.ranks[selected.baseId])}</DialogDescription><p className="equipment-affix">{equipmentText(selected)}</p><p>Quality {selected.quality}/3 · {selected.origin==='boss'?`Legacy boss mint · district ${selected.district}`:selected.origin==='safehouse'?'Minted at the safehouse':'Starter equipment'}</p><button className="primary-button" disabled={active||equippedItem(run,selected.slot)?.id===selected.id} onClick={()=>{onEquip(selected.id);setSelected(null);}}>{active?'Equip before your next climb':equippedItem(run,selected.slot)?.id===selected.id?'Equipped':'Equip item'}<Shield size={17}/></button></>}</DialogContent></Dialog></section>;
}
export function BossUpgradePanel({run,onUpgrade,onSkip}:{run:Run;onUpgrade:()=>void;onSkip:()=>void}){
 const offer=run.upgradeOffer;if(!offer)return <p className="risk-copy">{run.chapter===9?'The climb is complete. Temporary upgrades reset when you secure Alpha City.':'Secure this district to continue the climb.'}</p>;
 const id=run.gear[offer.slot]!;
 return <section className="boss-mint" aria-live="polite"><div className="mint-heading"><Sparkles/><div><span className="small-label">FIELD OVERCLOCK · THIS CLIMB ONLY</span><h3>{offer.resolved?(offer.purchased?'Upgrade installed':'Credits preserved'):'Upgrade recovered equipment'}</h3></div></div><div className="field-upgrade"><EquipmentArt id={id}/><div><span>{offer.slot} · randomly selected from your equipped gear</span><h4>{itemFor(id).name}</h4><p>{upgradeBenefit(offer.slot)}</p><p>{climbBoost(run,offer.slot)} overclock{climbBoost(run,offer.slot)===1?'':'s'} installed on this slot.</p></div></div>{!offer.resolved&&<div className="mint-actions"><button className="primary-button" disabled={run.salvage<offer.cost} onClick={onUpgrade}>Install overclock · {offer.cost} credits</button><button className="secondary-button" onClick={onSkip}>Skip & keep credits</button></div>}{!offer.resolved&&run.salvage<offer.cost&&<p>Need {offer.cost-run.salvage} more operation credits. You can skip this upgrade.</p>}<small>This offer is fixed until you decide. Upgrades carry into the next district and reset on death or completion of the climb. No item is minted here.</small></section>;
}
export function SafehouseMintPanel({book,onMint}:{book:RecordBook;onMint:()=>void}){
 const item=book.inventory.find(i=>i.id===book.lastMintId);
 return <section className="safehouse-fabricator" aria-live="polite"><div><span className="small-label gold">REBEL FABRICATOR</span><h3>Mint new equipment</h3><p>Spend {SAFEHOUSE_MINT_COST} banked credits for a permanent item. Equip new gear before your next climb.</p><button className="primary-button" onClick={onMint} disabled={book.salvage<SAFEHOUSE_MINT_COST}><Gem size={16}/> Mint equipment · {SAFEHOUSE_MINT_COST}</button>{book.salvage<SAFEHOUSE_MINT_COST&&<small>{SAFEHOUSE_MINT_COST-book.salvage} more banked credits needed.</small>}<details><summary>Rarity odds & mint details</summary><p>Each slot: 20%. Quality 1–3: equal chance. In-game credits only; no NFT or blockchain transaction.</p><div className="rarity-odds">{RARITIES.map(r=><span key={r.name} style={{color:r.color}}><span>{r.tier} · {r.name}</span><b>{r.weight}%</b></span>)}</div></details></div>{item&&<div key={item.id} className="mint-reveal compact-reveal" style={{'--rarity':RARITIES[item.rarity].color} as CSSProperties}><EquipmentArt id={item.baseId}/><div><span>{RARITIES[item.rarity].name} · {item.slot}</span><h4>{itemFor(item.baseId).name}</h4><p>Quality {item.quality}/3</p><p>{equipmentText(item)}</p><strong><Check size={15}/> In your permanent inventory</strong></div></div>}</section>;
}
