import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,transition} from '../src/lib/game.ts';
import {combatFeedback} from '../src/lib/combat-feedback.ts';
import {starterInventory,SLOTS} from '../src/lib/equipment.ts';
function battle(hero='nodewalker'){let r=transition(transition(createRun(hero),{type:'begin'}),{type:'visit',id:'bridge'});r.combat.enemies=r.combat.enemies.slice(0,2);r.combat.hero={x:3,y:1};r.combat.enemies[0].x=4;r.combat.enemies[0].y=1;r.combat.enemies[1].x=4;r.combat.enemies[1].y=2;for(const e of r.combat.enemies)e.hp=e.maxHp=1000;r.combat.obstacles=[];delete r.combat.arena;delete r.combat.layout;delete r.combat.terrain;r.hp=r.maxHp=1000;r.combat.block=0;return r;}
test('new inventories have exactly two distinct-art options per slot',()=>{const items=starterInventory();assert.equal(items.length,10);for(const slot of SLOTS)assert.equal(items.filter(i=>i.slot===slot).length,2);assert.deepEqual(items.filter(i=>i.slot==='weapon').map(i=>i.baseId),['daggers','sword']);});
test('direct attacks and all faction signatures have a 2% double-damage boundary',()=>{for(const hero of ['glitchborn','chainbreaker','nodewalker','coinbroker'])for(const skill of [false,true]){const r=battle(hero),a={type:'attack',id:1,skill},normal=transition(r,a,()=>.02),critical=transition(r,a,()=>.019999);assert.notEqual(normal,r);assert.equal(critical.lastHits[0].damage,normal.lastHits[0].damage*2);assert.equal(normal.lastHits[0].critical,false);assert.ok(critical.lastHits.every(h=>h.critical));assert.match(combatFeedback(r,critical,a).title,/Critical/);}});
test('enemy criticals double weakened damage before guard, without doubling hazards',()=>{const r=battle();r.combat.enemies=r.combat.enemies.slice(0,1);const e=r.combat.enemies[0];e.intent=[r.combat.hero];e.intentDamage=20;e.weaken=25;r.combat.block=5;r.combat.hazards=[r.combat.hero];r.combat.hazardDamage=3;r.gear.charm='phoenix';r.gear.chassis='plate';const normal=transition(r,{type:'end'},()=>.02),critical=transition(r,{type:'end'},()=>0);assert.equal(normal.hp,1000-(15+3-5));assert.equal(critical.hp,1000-(30+3-5));assert.match(combatFeedback(r,critical,{type:'end'}).title,/critical/);});
test('invalid actions, jammed enemies and corruption do not roll criticals',()=>{const r=battle();let calls=0;assert.equal(transition(r,{type:'attack',id:999},()=>{calls++;return 0;}),r);for(const e of r.combat.enemies){e.jammed=1;e.poison=1;e.intent=[r.combat.hero];}const next=transition(r,{type:'end'},()=>{calls++;return 0;});assert.equal(calls,0);assert.equal(next.lastHits.length,0);});
test('lethal criticals retain feedback after combat is cleared',()=>{const r=battle();r.combat.enemies=r.combat.enemies.slice(0,1);r.combat.enemies[0].hp=1;const a={type:'attack',id:1,skill:true},next=transition(r,a,()=>0);assert.equal(next.combat,null);assert.match(combatFeedback(r,next,a).impacts.find(i=>i.enemyId===1).text,/CRIT/);});
