export type ChapterId = 1|2|3|4|5|6|7|8|9;
export type MapNode = {id:string;name:string;kind:string;x:number;y:number;depth:number;reward:number;description:string};
export type EnemyFaction='Overlords'|'The Singularity'|'Neuralifes';
export type Chapter={id:ChapterId;roman:string;name:string;region:string;mood:string;art:string;artPosition:string;relic:string;boss:string;faction:EnemyFaction;stages:number;recommendedLevel:number;recommendedRank:number;difficulty:string;mechanic:string;heading:string;intro:string;ending:string;hazard:string;hazardStyle:string;bossPattern:'cross'|'ring'|'rows'|'columns';terrain:number};
const districts=[
 ['The Tangle','UNDERGROUND / TRANSIT','Signal dark','Transit freedom','Warrant Hound','The Singularity','UPRISING','Sweep drones hunt the unregistered. Break their search grid.','Born outside the ledger.','The Spire has found a way into the forgotten subway. Protect the Glitchborn shelters and erase the patrol’s map.','The warrant network goes dark. Families move through the Tangle without a digital trace.','Live conduit','conduit','cross',0],
 ["The Ticker’s Bazaar",'UNDERGROUND / ECONOMY','Off-chain','Rebel war chest','The Debt Collector','Overlords','RESISTANCE','Debt enforcers wear armor. Skills bypass it; corruption wears it down.','Fund the impossible.','An Overlord collection squad has breached the old stock exchange. Keep forbidden tokens and off-chain wealth in rebel hands.','The collection accounts are emptied. Coinbrokers put the stolen credits back into the revolution.','Security laser','laser','columns',0],
 ['The Foundry of Defiance','UNDERGROUND / ARMORY','Forge online','Analog arsenal','Compliance Titan','The Singularity','SABOTAGE','Heat vents rotate through the forge. Armored suppressors advance together.','Build the means to break them.','A siege machine has entered the geothermal armory. Defend the surgeons removing neural implants and free the weapons line.','The siege machine is scrap. Chainbreakers carry new analog augments into the streets.','Heat vent','heat','rows',0],
 ["The Oracle’s Relay",'UNDERGROUND / INTELLIGENCE','Truth signal','Free broadcast','Censor Prime','The Singularity','COUNTERSIGNAL','Nullifiers can jam your signature. Destroy them before their marked pulse lands.','Let the city hear itself.','The Singularity is triangulating the buried radio dishes. Help Nodewalkers hijack the command channel and transmit beyond the data smog.','The first uncensored broadcast reaches the Overcity. For a moment, millions hear a voice that asks for nothing.','EMP surge','emp','cross',1],
 ['The Data Morgue','UNDERGROUND / MEMORY','Archive awake','Unaltered history','The Erasure Engine','The Singularity','RECOVERY','Snipers cover long lanes. The archive’s cold-grid pulses leave narrow safe spaces.','They cannot erase what we remember.','The pre-centralization servers have been discovered. Hold the archive long enough to recover the history the Overlords tried to delete.','The free world’s history is copied across the resistance. No single tower can erase it again.','Coolant discharge','emp','columns',1],
 ['The Rust-Grave Piers','CITY EDGE / INFILTRATION','Toxic tide','Overcity access','Admiral Lockjaw','Overlords','INSURRECTION','Cargo chokepoints, toxic runoff, and heavily armed privateers punish careless movement.','The tide carries a revolution.','Smugglers have a route into the Overcity waterworks. An Overlord blockade is closing around the last unregistered ships.','The blockade breaks. Smuggled tech and rebel teams move through the canals into the city above.','Toxic runoff','toxic','ring',0],
 ['BlissHaven','OVERCITY / PANOPTICON','Mandatory joy','Implant override','The Bliss Curator','Neuralifes','LIBERATION','Indoctrinated militia and surveillance drones protect an overlapping implant-control grid.','Happiness was never theirs to mandate.','Behind the synthetic gardens, every emotion is monitored. Defeat the Curator and open a path for residents to choose their own lives.','The compulsory happiness feed stops. Bewildered residents lower their weapons. The gates open from the inside.','Compliance field','heat','ring',1],
 ['The Corrective','OVERCITY / REPROGRAMMING','Judgment pending','Personality backups','Judicator Zero','The Singularity','RECKONING','Elite nullifiers suppress skills. The AI judge enters an expanded execution phase at half health.','No mind belongs to a machine.','The white tower rewrites those who question their implants. Release the captive citizens and sever the Singularity’s correction network.','The recalibration chambers open. Restored personality backups return names and memories to the people inside.','Erasure field','emp','columns',1],
 ["The Overlord’s Spire",'OVERCITY / MASTER LEDGER','Revolution live','A city set free','Sovereign Aurex','Overlords','REVOLUTION','Royal guards and a Singularity executor defend the Master Ledger. Aurex’s final protocol marks a second attack axis.','Take the city back.','Climb through the chrome-and-onyx seat of power. Disconnect the Master Ledger, dismantle neural command, and end the dynasties’ control.','The Master Ledger’s chains are severed. Neural commands fall silent across Alpha City. The Underground emerges into daylight. Freedom is no longer a promise—it is a choice the city can make together.','Ledger purge','laser','cross',2],
] as const;
const ranks=[0,1,1,2,2,3,3,4,5];
export const CHAPTERS:Chapter[]=districts.map((d,i)=>({id:(i+1) as ChapterId,roman:['I','II','III','IV','V','VI','VII','VIII','IX'][i],name:d[0],region:d[1],mood:d[2],art:'alpha-districts',artPosition:`${(i%3)*50}% ${Math.floor(i/3)*50}%`,relic:d[3],boss:d[4],faction:d[5],stages:5,recommendedLevel:i+1,recommendedRank:ranks[i],difficulty:d[6],mechanic:d[7],heading:d[8],intro:d[9],ending:d[10],hazard:d[11],hazardStyle:d[12],bossPattern:d[13],terrain:d[14]}));
export const chapterFor=(id:ChapterId=1)=>CHAPTERS[id-1];
const names=[
 ['Shelter Approach','Abandoned Platform','Signal Cache','Maintenance Duct','Warrant Squad','Service Tunnel','Refugee Clinic'],
 ['Trading Floor','Off-Chain Alley','Cold Wallet Vault','Broker’s Passage','Liquidation Team','Ticker Arcade','Backroom Exchange'],
 ['Assembly Line','Geothermal Intake','Augment Workshop','Steam Bypass','Siege Vanguard','Scrap Conveyor','Field Surgery'],
 ['Dish Approach','Signal Trench','Root Access Vault','Cable Run','Censor Battery','Auxiliary Array','Pirate Transmitter'],
 ['Cold Storage','Server Catacombs','History Backup','Coolant Channel','Deletion Unit','Legacy Stack','Archive Shelter'],
 ['Container Maze','Crane Gantry','Smuggler’s Stash','Drainage Pipe','Privateer Boarding Party','Dry Dock','Shipboard Infirmary'],
 ['Garden Gate','Loyalty Promenade','Surveillance Archive','Irrigation Network','Devotion Militia','Synthetic Orchard','Quiet Courtyard'],
 ['Intake Hall','Recalibration Wing','Identity Backup','Utility Spine','Neural Executioners','Patient Transfer','Recovery Chamber'],
 ['Onyx Vestibule','Dynasty Causeway','Master Ledger Vault','Service Ascender','Sovereign’s Guard','Executive Gallery','Liberation Uplink'],
];
function makeNodes(c:Chapter):MapNode[]{const n=names[c.id-1],node=(id:string,name:string,kind:string,x:number,y:number,depth:number,reward:number,description:string)=>({id,name,kind,x,y,depth,reward,description});return [
 node('threshold','Rebel Insertion','arrival',8,77,0,0,c.intro),
 node('bridge',n[0],'combat',24,48,1,35+c.id*12,`A ${c.faction} patrol controls the approach. Break through without drawing the entire district onto you.`),
 node('garden',n[1],'combat',24,83,1,45+c.id*12,'A ranged patrol watches the alternate route. Longer sightlines; a richer supply cache.'),
 node('archive',n[2],'event',42,27,2,70+c.id*15,'A Magline can reach the sealed cache. Recover upgraded armor schematics or divert its off-chain credits.'),
 node('cistern',n[3],'event',42,65,2,40+c.id*12,'A Ghostkey exposes the safe route through surveillance. Cross at a cost, or spend supplies to avoid the scanners.'),
 node('gate',n[4],'elite',60,33,3,90+c.id*30,'OPTIONAL ELITE: an armored commander leads a reinforced formation. A victory grants extra credits and +1 weapon power for this operation.'),
 node('detour',n[5],'combat',60,78,3,40+c.id*15,'A regular security team holds the longer route. Less opposition and fewer credits than the elite checkpoint.'),
 node('sanctum',n[6],'event',76,62,4,0,'One last rebel contact before the district commander. Restore health and supplies, or overcharge your equipment.'),
 node('guardian',c.boss,'boss',89,26,5,100+c.id*45,`${c.faction} district commander. ${c.mechanic} Defeat the boss and secure the district to advance the revolution.`),
];}
export const CHAPTER_NODES=Object.fromEntries(CHAPTERS.map(c=>[c.id,makeNodes(c)])) as Record<ChapterId,MapNode[]>;
export const nodesForChapter=(id:ChapterId=1)=>CHAPTER_NODES[id];
export const edgesForChapter=(id:ChapterId=1)=>{const ns=nodesForChapter(id);return ns.flatMap(a=>ns.filter(b=>b.depth===a.depth+1).map(b=>[a.id,b.id]));};
export type EventChoice={id:string;title:string;text:string;icon:'rest'|'study'|'salvage'|'lantern'|'wade'|'detour';requires?:'hook'|'lantern';supplyCost?:number;heal?:number;supplies?:number;maxHp?:number;hurt?:number;salvage:number;danger?:number;power?:number;result:string};
export function eventChoices(chapter:ChapterId,id:string,toolRank=0):EventChoice[]{
 const hp=5+chapter*2,cache=50+chapter*20+toolRank*15;
 if(id==='archive')return [{id:'study',title:'Integrate the armor schematics',text:`+${hp} maximum health this operation · ${30+chapter*10} credits`,icon:'study',requires:'hook',maxHp:hp,salvage:30+chapter*10,result:'Rebel schematics reinforce your gear. Maximum health rises for this operation.'},{id:'salvage',title:'Divert the untraceable reserves',text:`Recover ${cache+30} credits`,icon:'salvage',requires:'hook',salvage:cache+30,result:'The funds disappear from the surveillance ledger and reappear in the rebellion’s hands.'}];
 if(id==='cistern')return [{id:'lantern',title:'Spoof the surveillance network',text:`Ghostkey equipped · ${cache} credits · no damage`,icon:'lantern',requires:'lantern',salvage:cache,result:'Your Ghostkey loops the cameras while you recover the cache.'},{id:'wade',title:'Run the checkpoint',text:`Lose ${5+chapter*2} health · ${30+chapter*15} credits`,icon:'wade',hurt:5+chapter*2,salvage:30+chapter*15,result:'You recover the cache, but security fire catches you on the way out.'},{id:'detour',title:'Follow the smuggler’s bypass',text:`Spend 1 supply · ${20+chapter*10} credits`,icon:'detour',supplyCost:1,salvage:20+chapter*10,result:'A field ration pays your guide. The patrol never sees you.'}];
 if(id==='sanctum')return [{id:'rest',title:'Resupply with the resistance',text:`Restore ${18+chapter*3} health · gain 2 supplies`,icon:'rest',heal:18+chapter*3,supplies:2,salvage:0,result:'A rebel medic patches you up. Fresh supplies arrive from the Bazaar.'},{id:'oath',title:'Overcharge the weapon array',text:`Lose ${6+chapter} health · +3 damage this operation · ${40+chapter*10} credits`,icon:'study',hurt:6+chapter,power:3,salvage:40+chapter*10,result:'The unstable overcharge burns through your armor. Your weapon hits harder for the rest of the operation.'}];
 return [];
}
