#[test_only]
module moonordie::moonordie_tests {
    use moonordie::moonordie::{Self, Commitment};
    use sui::clock::{Self, Clock};
    use sui::coin::{Self, Coin};
    use sui::sui::SUI;
    use sui::test_scenario::{Self, Scenario};

    const CREATOR: address = @0xCAFE;
    const BENEFICIARY: address = @0xBEEF;
    const KEEPER: address = @0xD00D;
    const DEADLINE: u64 = 1_000_000;
    // Public test vector only; seed 0x0101...01 must never be used in production.
    const PUBKEY: vector<u8> = x"8a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c";
    // Generated by shared/moonordie-core.cjs with the public test seed above.
    const SIGNATURE: vector<u8> = x"e227a11fd8bed62f6d97f96578e320104b845ef2cb5c0e33cc03b5246fcc356a0b0e7b973b8af78c9bd37e8b706474ed6c93a7a2c1895684546376816b50d90c";

    fun setup(): Scenario {
        let mut s = test_scenario::begin(CREATOR);
        let ctx = s.ctx();
        let mut clock = clock::create_for_testing(ctx);
        clock::increment_for_testing(&mut clock, 1_000);
        moonordie::create(coin::mint_for_testing<SUI>(500_000, ctx), BENEFICIARY,
            1_000_000, DEADLINE, 10_000, hash(), vector[PUBKEY], 1, b"test",
            &clock, ctx);
        clock::share_for_testing(clock);
        test_scenario::next_tx(&mut s, KEEPER);
        s
    }

    fun hash(): vector<u8> {
        x"0707070707070707070707070707070707070707070707070707070707070707"
    }

    #[test]
    fun javascript_signed_observation_unlocks_and_can_be_claimed_immediately() {
        let mut s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        let mut clock = s.take_shared<Clock>();
        clock::increment_for_testing(&mut clock, 500);
        moonordie::submit_success(&mut c, 1_000_000, 1_500, vector[0], vector[SIGNATURE], &clock);
        assert!(moonordie::status(&c) == 1, 0);
        moonordie::claim(&mut c, s.ctx());
        test_scenario::return_shared(clock);
        test_scenario::return_shared(c);
        test_scenario::next_tx(&mut s, BENEFICIARY);
        assert!(coin::burn_for_testing(s.take_from_sender<Coin<SUI>>()) == 500_000, 1);
        s.end();
    }

    #[test, expected_failure(abort_code = 4, location = moonordie)]
    fun signed_value_cannot_be_tampered_with() {
        let s = setup(); let mut c = s.take_shared<Commitment<SUI>>();
        let mut clock = s.take_shared<Clock>();
        clock::increment_for_testing(&mut clock, 500);
        moonordie::submit_success(&mut c, 1_000_001, 1_500, vector[0], vector[SIGNATURE], &clock);
        test_scenario::return_shared(c); test_scenario::return_shared(clock); s.end();
    }

    #[test, expected_failure(abort_code = 1, location = moonordie)]
    fun signed_success_cannot_be_replayed() {
        let s = setup(); let mut c = s.take_shared<Commitment<SUI>>();
        let mut clock = s.take_shared<Clock>();
        clock::increment_for_testing(&mut clock, 500);
        moonordie::submit_success(&mut c, 1_000_000, 1_500, vector[0], vector[SIGNATURE], &clock);
        moonordie::submit_success(&mut c, 1_000_000, 1_500, vector[0], vector[SIGNATURE], &clock);
        test_scenario::return_shared(c); test_scenario::return_shared(clock); s.end();
    }

    #[test, expected_failure(abort_code = 4, location = moonordie)]
    fun missing_signatures_cannot_unlock() {
        let s = setup(); let mut c = s.take_shared<Commitment<SUI>>();
        let clock = s.take_shared<Clock>();
        moonordie::submit_success(&mut c, 1_000_000, 1_000, vector[], vector[], &clock);
        test_scenario::return_shared(c); test_scenario::return_shared(clock); s.end();
    }

    #[test]
    fun success_claims_all_to_beneficiary_after_deadline() {
        let mut s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::succeed_for_testing(&mut c, 1_000_000, 1_500, 1_500);
        assert!(moonordie::status(&c) == 1, 0);
        let mut clock = s.take_shared<Clock>();
        clock::increment_for_testing(&mut clock, DEADLINE * 2);
        moonordie::claim(&mut c, s.ctx());
        assert!(moonordie::status(&c) == 2 && moonordie::balance_value(&c) == 0, 1);
        test_scenario::return_shared(c);
        test_scenario::return_shared(clock);
        test_scenario::next_tx(&mut s, BENEFICIARY);
        let paid = s.take_from_sender<Coin<SUI>>();
        assert!(coin::burn_for_testing(paid) == 500_000, 2);
        s.end();
    }

    #[test]
    fun disposal_at_deadline_creates_an_immutable_coin_with_the_entire_deposit() {
        let mut s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        let mut clock = s.take_shared<Clock>();
        clock::increment_for_testing(&mut clock, DEADLINE - 1_000);
        moonordie::dispose(&mut c, &clock, s.ctx());
        assert!(moonordie::status(&c) == 3 && moonordie::balance_value(&c) == 0, 0);
        let frozen_id = moonordie::disposed_coin(&c).destroy_some();
        test_scenario::return_shared(c);
        test_scenario::return_shared(clock);
        test_scenario::next_tx(&mut s, CREATOR);
        let frozen = s.take_immutable<Coin<SUI>>();
        assert!(sui::object::id_address(&frozen) == frozen_id, 1);
        assert!(coin::value(&frozen) == 500_000, 2);
        test_scenario::return_immutable(frozen);
        s.end();
    }

    #[test, expected_failure(abort_code = 2, location = moonordie)]
    fun cannot_dispose_early() {
        let mut s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        let clock = s.take_shared<Clock>();
        moonordie::dispose(&mut c, &clock, s.ctx());
        test_scenario::return_shared(c); test_scenario::return_shared(clock); s.end();
    }

    #[test, expected_failure(abort_code = 2, location = moonordie)]
    fun cannot_record_success_at_deadline_even_with_earlier_evidence() {
        let s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::succeed_for_testing(&mut c, 1_000_000, DEADLINE - 1, DEADLINE);
        test_scenario::return_shared(c); s.end();
    }

    #[test, expected_failure(abort_code = 1, location = moonordie)]
    fun success_can_never_be_disposed() {
        let mut s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::succeed_for_testing(&mut c, 1_000_000, 1_500, 1_500);
        let mut clock = s.take_shared<Clock>();
        clock::increment_for_testing(&mut clock, DEADLINE);
        moonordie::dispose(&mut c, &clock, s.ctx());
        test_scenario::return_shared(c); test_scenario::return_shared(clock); s.end();
    }

    #[test, expected_failure(abort_code = 1, location = moonordie)]
    fun pending_cannot_be_claimed() {
        let mut s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::claim(&mut c, s.ctx());
        test_scenario::return_shared(c); s.end();
    }

    #[test, expected_failure(abort_code = 1, location = moonordie)]
    fun disposed_cannot_be_claimed() {
        let mut s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        let mut clock = s.take_shared<Clock>();
        clock::increment_for_testing(&mut clock, DEADLINE);
        moonordie::dispose(&mut c, &clock, s.ctx());
        moonordie::claim(&mut c, s.ctx());
        test_scenario::return_shared(c); test_scenario::return_shared(clock); s.end();
    }

    #[test, expected_failure(abort_code = 1, location = moonordie)]
    fun cannot_claim_twice() {
        let mut s = setup();
        let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::succeed_for_testing(&mut c, 1_000_000, 1_500, 1_500);
        moonordie::claim(&mut c, s.ctx());
        moonordie::claim(&mut c, s.ctx());
        test_scenario::return_shared(c); s.end();
    }

    #[test, expected_failure(abort_code = 3, location = moonordie)]
    fun below_target_cannot_unlock() {
        let s = setup(); let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::succeed_for_testing(&mut c, 999_999, 1_500, 1_500);
        test_scenario::return_shared(c); s.end();
    }

    #[test, expected_failure(abort_code = 3, location = moonordie)]
    fun stale_observation_cannot_unlock() {
        let s = setup(); let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::succeed_for_testing(&mut c, 1_000_000, 1_500, 121_501);
        test_scenario::return_shared(c); s.end();
    }

    #[test, expected_failure(abort_code = 3, location = moonordie)]
    fun predeposit_observation_cannot_unlock() {
        let s = setup(); let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::succeed_for_testing(&mut c, 1_000_000, 999, 1_500);
        test_scenario::return_shared(c); s.end();
    }

    #[test, expected_failure(abort_code = 3, location = moonordie)]
    fun future_observation_cannot_unlock() {
        let s = setup(); let mut c = s.take_shared<Commitment<SUI>>();
        moonordie::succeed_for_testing(&mut c, 1_000_000, 1_501, 1_500);
        test_scenario::return_shared(c); s.end();
    }

    #[test, expected_failure(abort_code = 4, location = moonordie)]
    fun forged_signature_cannot_unlock() {
        let s = setup(); let mut c = s.take_shared<Commitment<SUI>>();
        let clock = s.take_shared<Clock>();
        moonordie::submit_success(&mut c, 1_000_000, 1_000, vector[0], vector[vector[]], &clock);
        test_scenario::return_shared(c); test_scenario::return_shared(clock); s.end();
    }
}
